// FILE: src/lib/audit-events.ts
// STAGE: 13
// UPDATED: 2026-10-02

export const AUDIT_EVENTS = {
  // Printers
  PRINTER_PAIRED: 'PRINTER_PAIRED',
  PRINTER_UNPAIRED: 'PRINTER_UNPAIRED',
  PRINTER_STATUS_CHANGED: 'PRINTER_STATUS_CHANGED',
  // Receipts
  RECEIPT_CREATED: 'RECEIPT_CREATED',
  RECEIPT_PRINTED: 'RECEIPT_PRINTED',
  RECEIPT_REPRINTED: 'RECEIPT_REPRINTED',
  RECEIPT_PDF_DOWNLOADED: 'RECEIPT_PDF_DOWNLOADED',
} as const;

export type AuditEvent = keyof typeof AUDIT_EVENTS;
